# Generated by Django 5.0.6 on 2024-07-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authfname', models.CharField(max_length=200)),
                ('authlname', models.CharField(max_length=200)),
                ('bname', models.CharField(max_length=200)),
                ('book_year', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
