# Generated by Django 5.0.6 on 2024-07-11 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opa', '0002_books_delete_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
