# Generated by Django 5.0.6 on 2024-07-13 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opa', '0003_rename_books_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='opa.book')),
            ],
            bases=('opa.book', models.Model),
        ),
    ]
