# Generated by Django 5.0.6 on 2024-07-13 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opa', '0004_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
